### ISSUE TITLE
Bootcamp 愛媛の場所が違うようなきがする

### ISSUE THREAD

**Issue by terapyon** [pyconjp/www.pycon.jp#5]
https://www.pycon.jp/support/bootcamp.html
Python Boot Camp in 愛媛
開催日: 2016年7月30日(土)
会場: 元町珈琲 松山中央の離れ

とありますが、
サイボウズ・ラボの愛媛で開催したとおもう。

ここに書かれた経緯をしりたいです。
@takanory 理由がわかりますか？

**Comment by takanory** [comment]
とくにおぼえてないですが、どっかからコピペしたんでしょうねぇ

**Comment by takanory** [comment]
イベントの場所にそう書いてある http://pyconjp.connpass.com/event/34564/

**Comment by terapyon** [comment]
原因がわかりました。主催者が別のイベントをやる時に、会場を編集してしまったパターンですね。

**Comment by takanory** [comment]
@terapyon 対応しました https://www.pycon.jp/support/bootcamp.html

**Comment by terapyon** [comment]
確認しました。ありがとうございます。
